
#ifndef __images_gfx__
#define __images_gfx__
#include <stdint.h>

#define images_gfx_transparent_color_index 255

#define Air_0_width 20
#define Air_0_height 20
#define Air_0_size 402
extern uint8_t Air_0_data[402];
#define Air_0 ((gfx_sprite_t*)Air_0_data)
#define Air_1_width 20
#define Air_1_height 20
#define Air_1_size 402
extern uint8_t Air_1_data[402];
#define Air_1 ((gfx_sprite_t*)Air_1_data)
#define Stone_width 20
#define Stone_height 20
#define Stone_size 402
extern uint8_t Stone_data[402];
#define Stone ((gfx_sprite_t*)Stone_data)
#define Grass_width 20
#define Grass_height 20
#define Grass_size 402
extern uint8_t Grass_data[402];
#define Grass ((gfx_sprite_t*)Grass_data)
#define Dirt_width 20
#define Dirt_height 20
#define Dirt_size 402
extern uint8_t Dirt_data[402];
#define Dirt ((gfx_sprite_t*)Dirt_data)
#define Cobblestone_width 20
#define Cobblestone_height 20
#define Cobblestone_size 402
extern uint8_t Cobblestone_data[402];
#define Cobblestone ((gfx_sprite_t*)Cobblestone_data)
#define Oak_width 20
#define Oak_height 20
#define Oak_size 402
extern uint8_t Oak_data[402];
#define Oak ((gfx_sprite_t*)Oak_data)
#define Sapling_width 20
#define Sapling_height 20
#define Sapling_size 402
extern uint8_t Sapling_data[402];
#define Sapling ((gfx_sprite_t*)Sapling_data)
#define Bedrock_width 20
#define Bedrock_height 20
#define Bedrock_size 402
extern uint8_t Bedrock_data[402];
#define Bedrock ((gfx_sprite_t*)Bedrock_data)
#define Water_width 20
#define Water_height 15
#define Water_size 302
extern uint8_t Water_data[302];
#define Water ((gfx_sprite_t*)Water_data)
#define Lava_width 20
#define Lava_height 15
#define Lava_size 302
extern uint8_t Lava_data[302];
#define Lava ((gfx_sprite_t*)Lava_data)
#define Sand_width 20
#define Sand_height 20
#define Sand_size 402
extern uint8_t Sand_data[402];
#define Sand ((gfx_sprite_t*)Sand_data)
#define Gravel_width 20
#define Gravel_height 20
#define Gravel_size 402
extern uint8_t Gravel_data[402];
#define Gravel ((gfx_sprite_t*)Gravel_data)
#define Gold_width 20
#define Gold_height 20
#define Gold_size 402
extern uint8_t Gold_data[402];
#define Gold ((gfx_sprite_t*)Gold_data)
#define Iron_width 20
#define Iron_height 20
#define Iron_size 402
extern uint8_t Iron_data[402];
#define Iron ((gfx_sprite_t*)Iron_data)
#define Coal_width 20
#define Coal_height 20
#define Coal_size 402
extern uint8_t Coal_data[402];
#define Coal ((gfx_sprite_t*)Coal_data)
#define Leaves_width 20
#define Leaves_height 20
#define Leaves_size 402
extern uint8_t Leaves_data[402];
#define Leaves ((gfx_sprite_t*)Leaves_data)
#define Sponge_width 20
#define Sponge_height 20
#define Sponge_size 402
extern uint8_t Sponge_data[402];
#define Sponge ((gfx_sprite_t*)Sponge_data)
#define Glass_width 20
#define Glass_height 20
#define Glass_size 402
extern uint8_t Glass_data[402];
#define Glass ((gfx_sprite_t*)Glass_data)
#define Log_width 20
#define Log_height 20
#define Log_size 402
extern uint8_t Log_data[402];
#define Log ((gfx_sprite_t*)Log_data)
#define Steve_0_width 20
#define Steve_0_height 40
#define Steve_0_size 802
extern uint8_t Steve_0_data[802];
#define Steve_0 ((gfx_sprite_t*)Steve_0_data)
#define Steve_1_width 20
#define Steve_1_height 40
#define Steve_1_size 802
extern uint8_t Steve_1_data[802];
#define Steve_1 ((gfx_sprite_t*)Steve_1_data)
#define Steve_2_width 20
#define Steve_2_height 40
#define Steve_2_size 802
extern uint8_t Steve_2_data[802];
#define Steve_2 ((gfx_sprite_t*)Steve_2_data)
#define Steve_3_width 20
#define Steve_3_height 40
#define Steve_3_size 802
extern uint8_t Steve_3_data[802];
#define Steve_3 ((gfx_sprite_t*)Steve_3_data)
#define Steve_4_width 20
#define Steve_4_height 40
#define Steve_4_size 802
extern uint8_t Steve_4_data[802];
#define Steve_4 ((gfx_sprite_t*)Steve_4_data)
#define Steve_5_width 20
#define Steve_5_height 40
#define Steve_5_size 802
extern uint8_t Steve_5_data[802];
#define Steve_5 ((gfx_sprite_t*)Steve_5_data)
#define Logo_0_width 140
#define Logo_0_height 60
#define Logo_0_size 8402
extern uint8_t Logo_0_data[8402];
#define Logo_0 ((gfx_sprite_t*)Logo_0_data)
#define Logo_1_width 140
#define Logo_1_height 60
#define Logo_1_size 8402
extern uint8_t Logo_1_data[8402];
#define Logo_1 ((gfx_sprite_t*)Logo_1_data)
#define sizeof_images_gfx_pal 512
extern uint16_t images_gfx_pal[256];

#endif
